const seedProducts=[
{id:1,name:'Chicken Shawarma',category:'Shawarma',price:120,emoji:'🌯',recipe:{chicken:1,bread:1,sauce:0.2,vegetables:0.15}},
{id:2,name:'Beef Shawarma',category:'Shawarma',price:140,emoji:'🌯',recipe:{beef:1,bread:1,sauce:0.2,vegetables:0.15}},
{id:3,name:'Shawarma Meal',category:'Meals',price:190,emoji:'🍽️',recipe:{chicken:1,bread:1,fries:1,sauce:0.25,vegetables:0.15}},
{id:4,name:'French Fries',category:'Sides',price:80,emoji:'🍟',recipe:{fries:1}},
{id:5,name:'Soft Drink',category:'Drinks',price:50,emoji:'🥤',recipe:{drink:1}},
{id:6,name:'Extra Cheese',category:'Extras',price:25,emoji:'🧀',recipe:{cheese:1}}
];
const seedInventory=[{id:'chicken',name:'Chicken',unit:'kg',stock:20,reorder:5},{id:'beef',name:'Beef',unit:'kg',stock:15,reorder:5},{id:'bread',name:'Arabic bread',unit:'pc',stock:80,reorder:20},{id:'sauce',name:'Sauce',unit:'L',stock:10,reorder:2},{id:'vegetables',name:'Vegetables',unit:'kg',stock:12,reorder:3},{id:'fries',name:'Fries',unit:'kg',stock:15,reorder:4},{id:'drink',name:'Soft drinks',unit:'pc',stock:60,reorder:15},{id:'cheese',name:'Cheese',unit:'pc',stock:50,reorder:10}];
const load=(key, fallback)=>JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));let products=load('products',seedProducts), inventory=load('inventory',seedInventory), sales=load('sales',[]), cart=[];let category='All';
const money=n=>`₱${Number(n||0).toFixed(2)}`;const $=id=>document.getElementById(id);function save(){localStorage.setItem('products',JSON.stringify(products));localStorage.setItem('inventory',JSON.stringify(inventory));localStorage.setItem('sales',JSON.stringify(sales))}function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)}
function renderCategories(){let cats=['All',...new Set(products.map(p=>p.category))];$('categories').innerHTML=cats.map(c=>`<button class="${category===c?'active':''}" data-category="${c}">${c}</button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;render()})}
function renderProducts(){let q=$('search').value.toLowerCase();let list=products.filter(p=>(category==='All'||p.category===category)&&p.name.toLowerCase().includes(q));$('products').innerHTML=list.map(p=>`<button class="product" data-product="${p.id}"><span class="emoji">${p.emoji}</span><h3>${p.name}</h3><p>${p.category}</p><div class="price">${money(p.price)}</div></button>`).join('')||'<p class="muted">No menu items found.</p>';document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>add(Number(b.dataset.product)))}
function add(id){let p=products.find(x=>x.id===id), item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});renderCart();toast(`${p.name} added`)}function changeQty(id,delta){let i=cart.find(x=>x.id===id);i.qty+=delta;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);renderCart()}function totals(){return cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0)}
function renderCart(){if(!cart.length)$('cart').innerHTML='<div class="empty">Your order is empty.<br>Select an item to begin.</div>';else $('cart').innerHTML=cart.map(i=>{let p=products.find(x=>x.id===i.id);return `<div class="cart-item"><div><h4>${p.name}</h4><small>${money(p.price)} each</small></div><div class="qty"><button data-minus="${p.id}">−</button><span>${i.qty}</span><button data-plus="${p.id}">+</button></div><div class="item-total">${money(p.price*i.qty)}</div></div>`}).join('');document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>changeQty(Number(b.dataset.minus),-1));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>changeQty(Number(b.dataset.plus),1));$('subtotal').textContent=money(totals());$('total').textContent=money(totals());updateChange()}
function updateChange(){let t=totals(),received=Number($('cashReceived').value||0);$('change').textContent=money(Math.max(0,received-t))}function renderInventory(){let low=inventory.filter(i=>i.stock<=i.reorder);$('lowStockCount').textContent=`${low.length} low stock`;$('inventoryList').innerHTML=inventory.map(i=>`<div class="inventory-row"><strong>${i.name}</strong><span class="muted">${i.unit}</span><span class="${i.stock<=i.reorder?'low':''}">${i.stock}</span><span class="muted">Reorder at ${i.reorder}</span></div>`).join('')}
function renderSales(){let today=sales.reduce((s,x)=>s+x.total,0),cash=sales.filter(x=>x.payment==='Cash').reduce((s,x)=>s+x.total,0),gcash=sales.filter(x=>x.payment==='GCash').reduce((s,x)=>s+x.total,0);$('todayTotal').textContent=money(today);$('salesList').innerHTML=`<div class="sale-row"><strong>Total</strong><strong>${sales.length} orders</strong><strong>${money(cash)} cash</strong><strong>${money(gcash)} GCash</strong></div>`+(sales.slice().reverse().map(x=>`<div class="sale-row"><strong>#${x.number}</strong><span class="muted">${new Date(x.date).toLocaleString()}</span><span>${x.payment}</span><strong>${money(x.total)}</strong></div>`).join('')||'<div class="empty">No completed sales yet.</div>')}
function printReceipt(sale){let lines=sale.items.map(i=>`<tr><td>${i.qty} × ${i.name}</td><td>${money(i.price*i.qty)}</td></tr>`).join('');let w=window.open('','receipt','width=360,height=600');if(!w){toast('Allow pop-ups to print the receipt');return}w.document.write(`<html><head><title>Receipt #${sale.number}</title><style>body{font-family:monospace;width:280px;margin:20px auto}h2{text-align:center;margin:0}p{text-align:center;font-size:12px}table{width:100%;border-collapse:collapse}td{padding:5px 0}td:last-child{text-align:right}.total{border-top:1px dashed #000;font-weight:bold}</style></head><body><h2>HAPPY SHAWARMA</h2><p>Customer Receipt<br>${new Date(sale.date).toLocaleString()}<br>Order #${sale.number}</p><table>${lines}<tr class="total"><td>TOTAL</td><td>${money(sale.total)}</td></tr><tr><td>${sale.payment}</td><td>${money(sale.paid)}</td></tr>${sale.payment==='Cash'?`<tr><td>CHANGE</td><td>${money(sale.change)}</td></tr>`:''}</table><p>Thank you!</p><script>window.print();window.onafterprint=()=>window.close()<\/script></body></html>`);w.document.close()}
function checkout(){if(!cart.length)return toast('Add an item first');let total=totals(),payment=$('payment').value,paid=payment==='Cash'?Number($('cashReceived').value||0):total;if(payment==='Cash'&&paid<total)return toast('Cash received is less than the total');let number=1001+sales.length;let sale={number,total,payment,paid,change:paid-total,date:new Date().toISOString(),items:cart.map(i=>{let p=products.find(x=>x.id===i.id);return{name:p.name,price:p.price,qty:i.qty}})};cart.forEach(i=>{let p=products.find(x=>x.id===i.id);Object.entries(p.recipe).forEach(([id,qty])=>{let ing=inventory.find(x=>x.id===id);if(ing)ing.stock=Math.max(0,ing.stock-qty*i.qty)})});sales.push(sale);save();printReceipt(sale);cart=[];$('cashReceived').value='';render();toast('Sale completed')}
function render(){renderCategories();renderProducts();renderCart();renderInventory();renderSales()}document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab-panel').forEach(x=>x.classList.add('hidden'));$(b.dataset.tab+'Tab').classList.remove('hidden')});$('search').oninput=renderProducts;$('cashReceived').oninput=updateChange;$('payment').onchange=()=>{$('cashFields').style.display=$('payment').value==='Cash'?'block':'none';updateChange()};$('checkout').onclick=checkout;$('clearOrder').onclick=()=>{cart=[];renderCart()};$('resetBtn').onclick=()=>{if(confirm('Reset all demo products, stock, and sales?')){products=seedProducts;inventory=seedInventory;sales=[];cart=[];save();render();toast('Demo data reset')}};setInterval(()=>$('clock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),1000);render();
